### ISSUE TITLE
Main entry

### ISSUE THREAD

**Issue by Ferrarie** [michaelpittino/Formidable#1]
May I ask about the main entry about the framework?
1. Is there the correct method is "Formidable.FormidableProgram.Initialize()"?
2. The default usage: press keypad 4 7 8 9 to open or close different Modules?

**Comment by michaelpittino** [comment]
1. Since it's a class library there is no official entry point. But yes, `FormidableProgram.Initialize` is the intended entry point. You need to somehow make sure you call this function after you get the library injected into the game process (for example by editing existing assemblies in the `Managed` folder. But be aware that BattlEye probably detects that.)

2. When the registered keys are pressed the `Toggle` function of the corresponding module is invoked.

**Comment by Ferrarie** [comment]
Thanks for the reply and remind me of the BattEye.
